spring.application.name=dia
server.port=9090

# MySQL ?? ?? ?? ??
#spring.datasource.url=jdbc:mysql://localhost:3306/dia
#spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/dia
spring.datasource.username=root
spring.datasource.password=qwer1234
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.project.dia.model.vo,com.project.dia.model.dto
mybatis.configuration.map-underscore-to-camel-case=true

# ?? ?? ??
spring.jackson.time-zone=Asia/Seoul
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# email-verify
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=sy_lee00
spring.mail.password=PCSSY7N33LX5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# log error check
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.project.dia=DEBUG

# SameSite=None?? ??? ???
# server.servlet.session.cookie.same-site=none
# (?? ??) localhost(HTTP)??? SameSite=None ??? ???
# ?? ??? http?? ??? ??. (????/?? ??? true? ??)
server.servlet.session.cookie.secure=false

# for keeping the login session
server.servlet.session.timeout=30m
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.path=/

